server:
  port: 8400
  servlet:
    context-path: /commitdemo
spring:
  application:
    name: sso-test-site
  devtools:
    restart:
      enabled: false
  thymeleaf:
    prefix: classpath:/templates
plugin:
  anti-duplicate-commit: 
    message: 页面超时请刷新重试!
  xss-filter:
    exclude:
      exclude-path: /demo/demoUpdateSubmit
  sensitive-word:
    word-file-location: sensitiveword.txt
    inva-char: '@#'
  email:
    mail-server-host: smtp.qq.com
    mail-server-port: 465
    mail-sender-address: 2567870363@qq.com
    mail-sender-username: 2567870363@qq.com
    mail-sender-password: mtwopskdwnjrdhgg
    mail-sender-nick: SLY
    ssl: true
    
    
      